USE HASTANETABLO;
CREATE TABLE HASTABILGI(
HASTAID INT PRIMARY KEY IDENTITY(1,1),
HASTAADI NVARCHAR(20),
HASTASOYADI NVARCHAR(20),
TCKIMLIKNO BIGINT UNIQUE,
HASTALIKADI NVARCHAR(50)
);

CREATE TABLE PERSONELBILGI(
PERSONELID INT PRIMARY KEY IDENTITY(1,1),
PERSONELAD NVARCHAR(20),
PERSONELSOYAD NVARCHAR(20),
PERSONELALANI NVARCHAR(100)
);

CREATE TABLE SAGLIKDURUMUBILGISI(
SAGLIKDURUMUID INT PRIMARY KEY IDENTITY(1,1),
SAGLIKDURUMU NVARCHAR (10)
);

CREATE TABLE HASTARANDEVULARI(
RANDEVUNO INT PRIMARY KEY IDENTITY(1,1),
HASTAID INT,
PERSONELID INT,
SAGLIKDURUMUID INT,
FOREIGN KEY (HASTAID) REFERENCES HASTABILGI(HASTAID),
FOREIGN KEY (PERSONELID) REFERENCES PERSONELBILGI(PERSONELID),
FOREIGN KEY (SAGLIKDURUMUID) REFERENCES SAGLIKDURUMUBILGISI(SAGLIKDURUMUID)
);

INSERT INTO HASTABILGI(HASTAADI,HASTASOYADI,TCKIMLIKNO,HASTALIKADI)
VALUES ('BETUL','AKMERCAN',12345678945,'REFLÜ'),
('ALPER','YILDIRIM',215313163264,'REFLÜ');
INSERT INTO PERSONELBILGI(PERSONELAD,PERSONELSOYAD,PERSONELALANI)
VALUES ('KEREM','YILDIZ','GASTROENTEROLOJI');
INSERT INTO SAGLIKDURUMUBILGISI(SAGLIKDURUMU)
VALUES ('NORMAL'),
('RAHATSIZ'),
('KRÝTÝK'),
('VEFAT');
INSERT INTO HASTARANDEVULARI(HASTAID,PERSONELID,SAGLIKDURUMUID)
VALUES (1,1,2),
(2,1,4);

SELECT * FROM PERSONELBILGI
SELECT * FROM HASTABILGI
SELECT * FROM SAGLIKDURUMUBILGISI
SELECT * FROM HASTARANDEVULARI

SELECT HASTABILGI.HASTAID,HASTABILGI.HASTAADI,HASTARANDEVULARI.PERSONELID,HASTARANDEVULARI.RANDEVUNO
FROM HASTABILGI
INNER JOIN HASTARANDEVULARI ON HASTABILGI.HASTAID = HASTARANDEVULARI.HASTAID
